### ISSUE TITLE
Bugged Inserting 

### ISSUE THREAD

**Issue by Zonharo** [nombersDev/casemove#104]
**MacOS ARM64 Ventura 13.4**

The ability to enter values when entering quantities is bugged, which makes the whole application lose its meaning because nothing can be transferred to the storage units

https://imgur.com/jdcsONw

**Comment by Zonharo** [comment]
Nothing can be entered in these values

**Comment by nombersDev** [comment]
You need to select a storage unit before entering anything in to the fields.
