### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by LInkerH** [nombersDev/casemove#105]
![image](https://user-images.githubusercontent.com/46254627/231378388-8293e12f-130f-4aee-9837-f2fbd3be4554.png)

I have the following problem, which only occurs on one account, while other accounts can display normally. I have tried reinstalling, changing networks, and changing machines, but none of them have solved the problem. 

The OS is win10, and app version is v2.1.1

**Comment by nombersDev** [comment]
Should be fixed with version 2.2.0
