### ISSUE TITLE
Linux Appimage of v2.2.0 is missing

### ISSUE THREAD

**Issue by hn46** [nombersDev/casemove#108]
The deb file is present but the Linux Appimage of v2.2.0 is missing. I'm using Arch Linux. Would you please upload the Appimage as well?

BTW, thank you very much for your hard work and contributing to the community. :heart: :heart: :heart:

**Comment by wazerstar** [comment]
same happens on windows, when you check for update it wants to download  blockmap instad of the exe file.

**Comment by sueskind** [comment]
> The internet connection is also working for me, don't know why. (I removed "discord" from PKGBUILD, as I don't want to install discord.)

I had to delete the `~/.config/casemove` directory and log in again, then it worked for me, too.

Removing the *discord* dependency is a good idea, I don't know why that would be included... I adjusted my comment above for people who don't read the whole thread.
