### ISSUE TITLE
Unknown error  Could be wrong credentials, a network error or something else.Error: LoggedInElsewhere

### ISSUE THREAD

**Issue by Vodka78420** [nombersDev/casemove#11]
All in title

**Comment by Vodka78420** [comment]
lastest version and same error with previous 1.2.0

**Comment by nombersDev** [comment]
LoggedInElsewhere means that the account is currently playing  / idling a game on the account that you're logging in to. This is not allowed. This is not a bug.

**Comment by steam69** [comment]
什么意思将其关闭什么
