### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Y-H3009** [nombersDev/casemove#113]
I have the following problem  
![problem](https://user-images.githubusercontent.com/95909809/233390902-b3973722-0785-4dee-81f4-2bd599ebec44.png)
The OS is win10, and app version is v2.2.1

**Comment by wazerstar** [comment]
Roll back to [2.1.1](https://github.com/nombersDev/casemove/releases/tag/2.1.1)

I had same problem, 2 releases after I have troubles logging in with.

**Comment by nombersDev** [comment]
Try deleting any old stored accounts and restart the app. Also try with other methods. Login token should always work as a last ditch effort. However, please report back if deleting the account solves the issue.

**Comment by wazerstar** [comment]
> Try deleting any old stored accounts and restart the app. Also try with other methods. Login token should always work as a last ditch effort. However, please report back if deleting the account solves the issue.

For windows I tried this, did not work, however I did go into %appdata% and delete the folder casemove, start casemove again with latest version today and it now works on latest release.

**Comment by Y-H3009** [comment]
> 尝试删除所有旧的存储帐户并重新启动应用程序。也可以尝试其他方法。登录令牌应始终作为最后的努力。但是，如果删除帐户可以解决问题，请反馈。

Delete the old account, after the restart process to re-enter account, program has been able to run normally
