### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kong317258437** [nombersDev/casemove#115]
I will report an error when I open it
![1](https://user-images.githubusercontent.com/98611378/233761878-ab3441e3-cdfc-41e1-9fa4-62e331a32f16.png)

**Comment by kong317258437** [comment]
win10 v2.21

**Comment by nombersDev** [comment]
Your system needs to have powershell installed and you need to have it added to system "PATH" for the app to run.  

Add %SystemRoot%/system32/WindowsPowerShell/v1.0 to your PATH Variable,

- cmd+q and search env and hit enter
- click environment variables in the advanced tab
- find Path/PATH variable and click edit
- Click new and paste %SystemRoot%/system32/WindowsPowerShell/v1.0
- click ok and restart your terminal and try installing again

I'm not able to offer further support for how to do this.
