### ISSUE TITLE
Still can't load Anubis collection

### ISSUE THREAD

**Issue by LInkerH** [nombersDev/casemove#117]
![image](https://user-images.githubusercontent.com/46254627/234482080-bd7e7a8f-0443-4948-9168-ce34bcada9a6.png)

**Comment by nombersDev** [comment]
That is because you're not downloading the latest items_game.txt files from Github do to your network. I'll update the backup files at some point in the near future.

**Comment by LInkerH** [comment]
How to download or configure manually?

**Comment by nombersDev** [comment]
I will update it tonight or tomorrow

**Comment by LInkerH** [comment]
> I will update it tonight or tomorrow

thanks a lot

**Comment by 2477332789** [comment]
2023major ！！！

**Comment by 2477332789** [comment]
please quick！！！！
