### ISSUE TITLE
Wrong quality assignment for consumer grades for Anubis collection

### ISSUE THREAD

**Issue by brOmstar** [nombersDev/casemove#118]
All Consumer Grades are identified as Industrial. Therefore wrong outputs are shown in trades.

E.g. snippet from collections.json: 

        "XM1014 | Hieroglyph": {
            "name": "XM1014 | Hieroglyph",
            "quality": "Industrial",
            "weaponType": "XM1014",

**Comment by nombersDev** [comment]
Fixed. Thanks for reporting
