### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by iam174cm** [nombersDev/casemove#120]
I have the same issue as Login problem #113, v2.2.2 and win10 64bit. Sure about this account not playing any games when login. I've tried deleting casemove in appdata folder and reinstall, it still not working with login. maybe still some issue with steam login?
![1](https://user-images.githubusercontent.com/132006351/234956710-fe50943b-38c4-4926-9d3a-6247c4497877.png)

**Comment by nombersDev** [comment]
If you have actually deleted it, the stored account on the right should not be there. Delete that try again. Otherwise it's either a steam issue. As a last resort you can login with the web token.

**Comment by iam174cm** [comment]
there's no account be remembered in the right though. i delete that and reinstall and try login for the first time and this error still exist. i tried login with web token and it keep processing sign in and nothing respond

**Comment by nombersDev** [comment]
Have you tried with qr?

**Comment by iam174cm** [comment]
i tried and it shows error analysing QR code on my steam guard which is on iPhone. and QR code looks like not changing now and then like it would be on steam client. I check login with steam client like usual and it's normal, which meams nothing wrong with my network and steam i think....
