### ISSUE TITLE
2023major

### ISSUE THREAD

**Issue by 2477332789** [nombersDev/casemove#124]
可以更新一下2023majo胶囊和纪念包纪念币吗

**Comment by nombersDev** [comment]
no

**Comment by 2477332789** [comment]
why？a lot of people need it.

**Comment by 2477332789** [comment]
please update  2023major capsule

**Comment by nombersDev** [comment]
I will update the files when I have time. Don't be entitled.

**Comment by 2477332789** [comment]
Why don't be entitled

**Comment by nombersDev** [comment]
Because I don't work for you. I will update it when I have the time, but it's not okay to spam previous issues with this. It's not going to make me update it faster.

**Comment by 2477332789** [comment]
Thank you ！
