### ISSUE TITLE
Possible to add a feature to filter by float before moving to or out of container

### ISSUE THREAD

**Issue by Stefanalf** [nombersDev/casemove#131]
Would help a lot in my case

**Comment by TheMuchi** [comment]
You can sort by float already. But you mean something like in the buff of csgofloat search where you define max an min float as a filter, right? This would be more convenient of course.

**Comment by nombersDev** [comment]
Yes, this feature is comming in the next major release.

**Comment by Stefanalf** [comment]
Thank you, thats awesome!
