### ISSUE TITLE
Is it possible to add the ability to buy a container?

### ISSUE THREAD

**Issue by webbfam** [nombersDev/casemove#133]
Is it possible to add the ability to buy a container?

**Comment by TheMuchi** [comment]
Duplicate of #58

**Comment by nombersDev** [comment]
Thanks for the tag @TheMuchi

**Comment by lmiol** [comment]
https://partner.steamgames.com/doc/webapi_overview#1
Steam web-api not restrict to use in game purchase but vice versa, they say it's allowed.
![image](https://github.com/nombersDev/casemove/assets/264879/a433fd3b-a79e-4c37-83e4-3bfe25308cf4)
So it is possible =)
