### ISSUE TITLE
Could be wrong credentials, a networkerror, the account playing another gameor something else.

### ISSUE THREAD

**Issue by dlc66** [nombersDev/casemove#141]
how to fix this？
![image](https://github.com/nombersDev/casemove/assets/79479304/53e04292-da2a-427d-a44b-b61f8b551e11)
I have already opened the VPN

**Comment by MrToWy** [comment]
Getting the same error for every login method.

**Comment by ByMykel** [comment]
I had the same error and I ended up installing [debugtron](https://github.com/pd4d10/debugtron) to debug the error.

My error was that after updating to latest version and having credentials saved from the previous version there was some error, so I just deleted the saved credentials and wrote the username and password again.

Your error might be different though.

**Comment by windwindwa** [comment]
I encountered the same problem and used debugtron to view the logs, resulting in the following error message

I positioned this mistake as coming from this function  [flowLoginRegular]( https://github.com/nombersDev/casemove/blob/main/src/main/helpers/login/loginRegular.tsx#L6C23-L6C39)

After searching Google, I found that this error may have come from the client successfully sending a message but not receiving a response from the server;
Can this be a problem with the local network? May I ask if it is possible to add a proxy option?

<img width="1249" alt="image" src="https://github.com/nombersDev/casemove/assets/48432322/4f6d98c2-c65e-46de-a1de-05eb75ae620a">
