### ISSUE TITLE
Some feature that I would like

### ISSUE THREAD

**Issue by Stefanalf** [nombersDev/casemove#142]
First of, thanks for developing this great tool to use!

The features in question I would like is: 
1. Able to sort by sticker price, atm you can only do by the amount of sticker and not price.
2. Sort price by single item and not only by the total amount * price.

Once again thanks for your work

**Comment by nombersDev** [comment]
Thank you for your kind words. Those would be good suggestion, would love to talk more about them on the discord if you ever feel like it :)
