### ISSUE TITLE
Multiple instance of casemove

### ISSUE THREAD

**Issue by xiaoxunlong** [nombersDev/casemove#144]
I want to move my items simultaneously in two or more accounts. So I want to launch multiple casemove in my computer. I try to use sandbox of avast to launch multiple instance. Although the task manager shows that the second casemove is opened, nothing shows up. Is casemove support multiple instance? If so, could the author provide some instructions to launch multiple instance of casemove? If don't, are there any possibles to launch multiple instance of casemove?

**Comment by xiaoxunlong** [comment]
Maybe a feasible solution is using virtural machine

**Comment by nombersDev** [comment]
That's intended behavior. If you want to disable it, you can build the application and turn off the check

**Comment by xiaoxunlong** [comment]
Thank you for your reply! Could you please tell me where the check is?
