### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LTGM** [nombersDev/casemove#155]
Hei
Can we please have an option to:
Load all items on the account including ALL containers
Select items we want (for example 1000 stickers)
For example inventory is 900/1000 full
Move these stickers to a selected container without a need to constantly move them by 100 or free up whole inventory to 0/1000 just for this sole purpose
Long time investors with large inventories will be immensely grateful for that

**Comment by darkylein** [comment]
You could just buy one or two new containers and sort your Inventory. So you can move your items more freely.

As you have probably already noted, there are sometimes items whose got missed (on steam side) when you move multiple items. I think it would be a lot of coding to take track of all of those items. Only my opinion.

**Comment by wing192** [comment]
I hope to mark every items with the price I purchased
