### ISSUE TITLE
infinite loading login screen

### ISSUE THREAD

**Issue by Tankonyako** [nombersDev/casemove#159]
hello, i just updated casemove, and have infinite loading screen (tried all methods of auth).

**Comment by masonvqnx** [comment]
mac os?

**Comment by masonvqnx** [comment]
i have that problem with ver 2.3.1 on mac os

**Comment by B-A-N-D-I-T** [comment]
Same with Ubuntu 23.10. Version 2.3.1 didn't fix anything for me

**Comment by Tankonyako** [comment]
> mac os?

yes macos

**Comment by Tankonyako** [comment]
on windows - all works

**Comment by changwei1122** [comment]
The same goes for Windows
![image](https://github.com/nombersDev/casemove/assets/159689257/6649bb19-4d9e-4d60-94b4-3068e1c26911)

**Comment by B-A-N-D-I-T** [comment]
I don't even have that popup

**Comment by nombersDev** [comment]
Please report bugs on the discord
