### ISSUE TITLE
not all selected items are moved

### ISSUE THREAD

**Issue by tanago** [nombersDev/casemove#26]
I wanted to insert 1000 cases in a new Storage Unit. It didnt move them all but around 700 instead. I had to repeat the operation multiple times to move all 1000 cases.

**Comment by nombersDev** [comment]
Did you use fastmove? How did it not move them? 

Did it say "700" remaining on the move pop-up at the start or did it say "1000" and then just 'freeze' (gets stuck at a specific number) at some point?

**Comment by tanago** [comment]
this happens on my PC, on my notebook the app works fine - just tested it.

On my PC the Popup with the count in the blue circle - the numbers decrease extremely rapidly but in the background - the storage unit count isn't in sync with it. 

The popup closes, allegedly moved all cases, but the storage unit count in the main screen still decreases for a couple of seconds more and stops before it has moved all the cases.

Hopefully I explained it well. I sold all the cases so cannot provide a video in the near future :(

**Comment by nombersDev** [comment]
On your PC, could you try and go to the settings and see if the option "Fastmove" is enabled?
