### ISSUE TITLE
Pricing and url problem with graffiti in "SWAT Blue" color

### ISSUE THREAD

**Issue by demiryasinoruc** [nombersDev/casemove#35]
There is a problem with graffiti in "SWAT Blue", the market hash name has the word "SWAT" as "Swat" so it doesn't show prices and the steamcommunity url (https://steamcommunity.com/market/listings/730/Sealed%20Graffiti%20%7C%20Smarmy%20%28Swat%20Blue%29) doesn't work

**Comment by nombersDev** [comment]
Have fixed it now, will be shipped with the next release. Thanks for letting me know.
