### ISSUE TITLE
Floats not correctly sorted

### ISSUE THREAD

**Issue by dill4u** [nombersDev/casemove#41]
v1.5.4

This is what is shown after I click "sort-by float"
![casemove](https://user-images.githubusercontent.com/21136430/163537388-d3d07cab-3b63-4175-8062-c338c5628e99.jpg)

It's sorted, but also grouped by product
Can we just ignore the grouping?

In my case, 
3 of my _"Glock-18 | Death Rattle"_ will be hard to find because they hide between hundreds of _"G3SG1 | Green Apple"_ and _"Nova | Caged Steel"_.

**Comment by nombersDev** [comment]
I'll figure out a fix. Does it work normally on the inventory page? 

Just as any FYI, if you're looking for specific floats, i'd recommend maximizing the window and using the float sliders / search bar to make it easier to find the skins you're looking for.

**Comment by dill4u** [comment]
Only Trade Up page..
Works normally on Inventory, Transfer To, and Transfer From pages. 

It's not like I search for specific skins / floats. 
What I usually do is picking the highest float ones as starting point for my trade up.

**Comment by nombersDev** [comment]
Should be fixed in version 1.6.0. Thanks for the bug report!
