### ISSUE TITLE
App not usable on smaller screen resolutions (1366x768) due to the window not being resizable 

### ISSUE THREAD

**Issue by JA-Marshall** [nombersDev/casemove#52]
Would it be possible to add support for smaller screen resolutions / add a way i can resize the window. On my laptop the buttons at the bottom aren't clickable on a resolution of 1366x768 and i cant resize the window to reach them

**Comment by nombersDev** [comment]
Sorry but I don't support screen resolutions that small currently and if I disabled the minimum width and height parameters, it would break the current design in many ways. If you want to disable this limit, I'm afraid that you'll have to build the app yourself and remove the lines:

`  minWidth: 1030,
    minHeight: 800,`
from [here](https://github.com/nombersDev/casemove/blob/main/src/main/main.ts)
