### ISSUE TITLE
Cant move antwerp causples in to units

### ISSUE THREAD

**Issue by Tonaka1** [nombersDev/casemove#53]
It dosent reconize any antwerp items but antwerp stickes is movable

**Comment by ADVSEB** [comment]
Hi, could you please create a video showcasing the issue and add it here?

**Comment by Tonaka1** [comment]
https://user-images.githubusercontent.com/106816153/171898148-d4acb8d4-5521-44e7-bee2-cead00efbfa6.mp4

soz for the explosive mic : (

**Comment by nombersDev** [comment]
Please try and download the app again, and let me know if it's fixed. I've updated the backup files that the app uses when your network fails to fetch the new versions.
