### ISSUE TITLE
App crahses after X Capsules transferred

### ISSUE THREAD

**Issue by niss1m** [nombersDev/casemove#54]
So basically when I transfer more than 300 capsules the app crashes after 80-90 capsules.

**Comment by niss1m** [comment]
https://gfycat.com/ThesePhonyAstrangiacoral

**Comment by ADVSEB** [comment]
Could you let me know if it's still there if you enable fastmove in the settings?

**Comment by nombersDev** [comment]
Could you let me know if it's still there if you enable fastmove in the settings?

**Comment by niss1m** [comment]
Nope, it does not occur when fastmove is enabled.

**Comment by MarvinKlein1508** [comment]
I'm having the same issue. Everytime I move some tiems I'll need to restart the app. It only shows a white window and freezes on Windows 11. In version 1.6.1 everything is working fine for me. In all other versions above this issue appears.

**Comment by niss1m** [comment]
> I'm having the same issue. Everytime I move some tiems I'll need to restart the app. It only shows a white window and freezes on Windows 11. In version 1.6.1 everything is working fine for me. In all other versions above this issue appears.

Yeah current fix is turning fast mode on.

**Comment by MarvinKlein1508** [comment]
@niss1m can I apply it to the program files, or do I'll need for a new release?

**Comment by nombersDev** [comment]
Has it only occured when transfering to storage units?

**Comment by nombersDev** [comment]
> @niss1m can I apply it to the program files, or do I'll need for a new release?

Fastmode is enabled by clicking on the account when logged in, clicking settings and toggling the option.

**Comment by MarvinKlein1508** [comment]
@nombersDev I had fastmode enabled in 1.6.1. Disable and enable this feature again did the trick for me.

**Comment by nombersDev** [comment]
Should be fixed in 1.6.5
