### ISSUE TITLE
Feature Request: Buy in-game items through casemove

### ISSUE THREAD

**Issue by niss1m** [nombersDev/casemove#58]
Buying in-game items through casemove can be a neat feature to have especially when you're not home.

**Comment by nombersDev** [comment]
Great feature. Won't be implemented due to legal reasons.

**Comment by lmiol** [comment]
https://partner.steamgames.com/doc/webapi_overview#1
Steam web-api not restrict to use in game purchase but vice versa, they say it's allowed.
![image](https://github.com/nombersDev/casemove/assets/264879/a433fd3b-a79e-4c37-83e4-3bfe25308cf4)
So it is possible =)
