### ISSUE TITLE
Bug from linux

### ISSUE THREAD

**Issue by LinarSharifullin** [nombersDev/casemove#65]
I can't enter a value in the field "move" to linux (Fedora Linux 36, GNOME42.2, wayland), other fields are working properly

**Comment by nombersDev** [comment]
You need to select (click on) the Storage Unit the app should move the items to before entering a number in the move field :)

**Comment by LinarSharifullin** [comment]
I had an error due to an overflowing inventory, I suggest making some kind of warning about this. And please reply in reddit
