### ISSUE TITLE
Overview page bugs and features

### ISSUE THREAD

**Issue by GODrums** [nombersDev/casemove#69]
Hey,

I've noticed some bugs and possible improvements in the new overpage page of the 2.0 update. I am also a Typescript developer, so if you are interested in some assistance I'd be free to help out.

Bugs:
- first of all the bar graph seems to not fill the whole area and the names are cut off if longer than a certain amount:
![Screenshot_bar_graph](https://user-images.githubusercontent.com/21990230/181668616-b319b961-3a13-4367-9762-ae396a8c97fe.png)
- secondly the pie chart displays a strage 0.00% category that cannot be removed:
![Screenshot_pie_chart](https://user-images.githubusercontent.com/21990230/181668734-4385e2b7-fcb9-4b81-a3bf-3d3abc58b7ef.png)

Feature:
- storing the collected data from the storage units, so they don't have to be reloaded every time the app is started

**Comment by TheMuchi** [comment]
I would add, that some prices when hovering over of the diagrams are rounded with 3 decimal places. That looks unusual.

**Comment by nombersDev** [comment]
Most of these are now added. Thank you for your suggestions/feedback.
