### ISSUE TITLE
Credentials login connection failed

### ISSUE THREAD

**Issue by Vodka78420** [nombersDev/casemove#7]
Am I the only one who have : 
"Unknown error. Could be wrong credentials, a network error or something else."

**Comment by nombersDev** [comment]
Which version of the app are you on and what is your OS? Also, which country are you from?

**Comment by Vodka78420** [comment]
I am used the lastest version 1.1.2 on windows 10 in France

**Comment by nombersDev** [comment]
I'm just going to spit out some questions here: 

Is your account already running CSGO or any other Steam game when you try to login? Does your account use 2 factor authentication, and if so, do you fill out the auth code field on the login page?  
Have you tried on other networks?

**Comment by Vodka78420** [comment]
Is your account already running CSGO or any other Steam game when you try to login? NO
Does your account use 2 factor authentication, and if so, do you fill out the auth code field on the login page? YES, STEAMGUARD
Have you tried on other networks? YES

**Comment by nombersDev** [comment]
Could you also please let me know if you encounter the same issue on the older versions?

**Comment by Vodka78420** [comment]
YES same error
Could you also please let me know if you encounter the same issue on the older versions?
NO

**Comment by nombersDev** [comment]
I need to be sure, does the problem exist on version 1.1.0

Does the problem exist on version 1.1.1?

**Comment by Vodka78420** [comment]
I dont know because when i was uninstalled it writed 1.1.0

**Comment by nombersDev** [comment]
Okay, based on the fact that the error message from Steam says "invalid password" this doesn't indicate an issue with the app itself, but with the entered data. I'd say remember that you need to use the exact same username and password that you use to login to Steam. 

What I'd also recommend is that you try to uninstall the app and reinstall it. You can also download a previous version from the releases page and try with these, though the result should be the same.
