### ISSUE TITLE
When logged into Casemove, Steam status is set to online in csgo

### ISSUE THREAD

**Issue by TheMuchi** [nombersDev/casemove#70]
Its a bit confusing, when my m8s are asking if I want to play a match but I only want to move some cases .

**Comment by nombersDev** [comment]
Unfortunately that isn't possible due to limitations from Steam :(

**Comment by TheMuchi** [comment]
But what changed from the pre 2.0 versions to the current version of casemove? Bc in the older versions I was not shown as online. Thanks for your fast response :)

**Comment by nombersDev** [comment]
I'll see what I can do. It can have something to do with the setpersona state, sometimes it's required to force the login, however, I'll see what happens if it turn it off after the connection is established. I'll let you know regardless :)
