### ISSUE TITLE
Unable to save login on manjar linux

### ISSUE THREAD

**Issue by TheMuchi** [nombersDev/casemove#71]
The casemove client does not remember my login. Even when I enable the option remember me for later.
If i remember right, the client shows your username in the right corner, even when you were logged out from the session. But this is not the case here. It only says "Nothing here...".
For me this looks like the client is unable to save persistent data at all.
I'm using version 2.0.0 of casemove and the current version of Manjaro Linux.

**Comment by nombersDev** [comment]
I'm sorry but Linux is really impossible for me to do generalized bugtesting/fixing on.
There are too many versions and way to many things that can go wrong depending on the specific setup. I can't really help here, unfortunately.
