### ISSUE TITLE
Browser login sets status to playing CS:GO, but doesn't log in

### ISSUE THREAD

**Issue by la-saga** [nombersDev/casemove#74]
When trying to use the browser login feature, the app hangs for a minute before returning the message "Your account is currently playing a game elsewhere". Attempting to log in changes my status to "playing cs:go" but doesn't finish the login, producing the message "you were logged in but the account is currently playing elsewhere". If I back out of the browser login screen and try again it logs me into what I assume is a dummy account.

Just in case... I'm not playing any games on Steam while attempting this ;)

[Screenshots](https://imgur.com/a/kK6HABO)

Thanks for doing what you do!

**Comment by nombersDev** [comment]
Have you experienced the issue with previous versions of Casemove? Does it always occur or are you sometimes able to log in?

**Comment by la-saga** [comment]
The same thing happens with v2.0, I haven’t tried 2.01 though. I didn’t experience the default login part on 2.0 fwiw.
