### ISSUE TITLE
Transfer | To - typing numbers in QTY field does not work.

### ISSUE THREAD

**Issue by wazerstar** [nombersDev/casemove#82]
Latest version 2.0.3 using the setup on both win11 and win10 pro does not allow to either copy numbers with ctrl+v or use numpad/keyboard to move desired items.

Transfer | From does however work.

**Comment by wazerstar** [comment]
Also as a suggestion, would be really cool to mark the QTY field and add scroll wheel up/down for numbers.

**Comment by nombersDev** [comment]
You would need to select a storage unit before selecting the qty, could you please confirm if this was the issue?

**Comment by wazerstar** [comment]
> You would need to select a storage unit before selecting the qty, could you please confirm if this was the issue?

You are right, not sure how I could miss this, maybe to prevent such user error add fade to that section and show highlight about select storage before using this.
