### ISSUE TITLE
10 Year Birthday Coin ist marked as moveable

### ISSUE THREAD

**Issue by TheMuchi** [nombersDev/casemove#84]
Looks like the birtday coin is not catgorized right.

**Comment by nombersDev** [comment]
As far as I'm aware the coin shouldn't be moveable

**Comment by TheMuchi** [comment]
It shouldn't show the birthday coin but it does. This is on windows
![image_2023-01-13_13-32-34](https://user-images.githubusercontent.com/87721408/212321324-eaab7814-8f59-4a19-9717-ae379921f666.png)

**Comment by J3fftw1** [comment]
Also seeing this. Case move shows that its a movable item and thinks its value is 0.

**Comment by TheMuchi** [comment]
By some magic the 10 years coin doe not appear as moveable anymore.
