### ISSUE TITLE
Can't login after choosing to "Login without closing" steam client

### ISSUE THREAD

**Issue by TheMuchi** [nombersDev/casemove#86]
Casemove aborts the login process and clears login field every time i retry to login, even when I close steam after my first attempt.
After closing steam client and restarting casemove everything works mostly fine. Sometimes I had to re-enter my Steam-Guard code.

**Comment by nombersDev** [comment]
I will test it out more, thanks for reporting it.

**Comment by nombersDev** [comment]
Should be fixed now
