### ISSUE TITLE
Customize columns in item table

### ISSUE THREAD

**Issue by GODrums** [nombersDev/casemove#88]
Something that's been bothering me for some time now has been the item table when moving stuff in and out of storage units. I would love to see a feature when you can customize which columns you want to see (e.g. disabling the price, stickers, tradehold columns).

When opening the app and selecting storage units in the "FROM" section, it gets impossible to read the item names.
Here an example with default resolution / sizing when opening the app on a 1920x1080 monitor:
![Screenshot_361](https://user-images.githubusercontent.com/21990230/212522506-576678b6-6585-45f3-aa3b-f067a3eb1d99.png)
As you can see, there is no way to differenciate which capsule is which.

**Comment by Songs5s** [comment]
It seems that it can be solved by stretching the border of the program window

**Comment by JamesMiralia** [comment]
> It seems that it can be solved by stretching the border of the program window

That's true, but I also want to resize the columns without resizing the window
