### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by SirFrasi** [nombersDev/casemove#91]
First of all, thank you for this very good software. This is just an idea to maybe make the project more useful.

I have read a lot that the software does not lead to a VAC ban and I am also convinced of it. Nevertheless, I find it unfortunate that it is not possible to use the program without logging in. Since there is already the export function, I would find it really useful if you could load this and analyze the statistics.

**Comment by TheMuchi** [comment]
Tbh I think that an offline mode shouldnt be integrated. Too much work for a probably barely used feature. 

Further the purpose of casemove is to move items. Analysis is a nice side effect and you can enjoy all the stats if you just login. If you want to repetitly do the same analysis again and again just extract the CSV and build your own code (e.g. with python) to do further analysis with that data.

**Comment by nombersDev** [comment]
> Nevertheless, I find it unfortunate that it is not possible to use the program without logging in

From a security pov, it's ultimately better that the program requires you to log in. You really wouldn't want an app, that doesn't log you in, to be able to do different actions on your account. That would be a security nightmare. What I'd recommend is to use the token to login. It's a one time string and really secure.

**Comment by SirFrasi** [comment]
I understand that and I can understand your point of view. However, I use the program exclusively to determine the value of my inventory. So not to make changes. That's why it's interesting for me to be able to see the value without logging in, since I've been holding my items for years and don't really change them.

The idea with the Python script is good, I think I will come up with something.

Thanks for the answers anyway :)

**Comment by TheMuchi** [comment]
Afaik you can not see items in a storage unit without logging into csgo as game coordinator. Without login you can only see items which are in your inventory like u see it on the web page. 
So if you don't have any storage units u could scrape your public inventory from the web page or use the steam web api to fetch the data directly.
