### ISSUE TITLE
Why does this problem keep happening?

### ISSUE THREAD

**Issue by ZJNOOB** [nombersDev/casemove#94]
Unknown error

Could be wrong credentials, a network error, the account playing another game or something else.

**Comment by nombersDev** [comment]
Please be more specific. There's really not a lot of information for me to work with here.

**Comment by ZJNOOB** [comment]
![image](https://user-images.githubusercontent.com/115875428/221403432-010deb39-8859-4d06-923a-9542d3a24f56.png)
just like this

**Comment by stev4kcs** [comment]
I also encountered the same problem. I was able to use it normally until last night, but it suddenly failed to move when I used it last night, and I couldn't log in again today.
![1](https://user-images.githubusercontent.com/95623542/221528701-f9f474b7-e567-48ba-9003-687d274218fd.jpg)

**Comment by steam69** [comment]
Me too

**Comment by Songs5s** [comment]
I also have a similar problem, the upper right corner shows that the login is successful but the login screen is still spinning in circles, and I can't open the toolbar on the left
![image](https://user-images.githubusercontent.com/126375074/222710716-d2c098ed-f991-4058-a93d-3392f2d8e640.png)

**Comment by Songs5s** [comment]
I also have a similar problem, the upper right corner shows that the login is successful but the login screen is still spinning in circles, and I can't open the toolbar on the left
![image](https://user-images.githubusercontent.com/126375074/222711166-44b18a5d-4560-4548-aa58-c19eb8b4ebbc.png)

**Comment by MrDumox** [comment]
i have the same problem

**Comment by nombersDev** [comment]
should be fixed with version 2.2.0
