### ISSUE TITLE
Feature request: See how many cases you have.

### ISSUE THREAD

**Issue by J3fftw1** [nombersDev/casemove#95]
Add a way to see how many you have of each case on the overview page:
Right now it only shows how much it worth, but it would also be super handy to see how many you have.

**Comment by TheMuchi** [comment]
You can see that already when you click on "Price" on the overview site and then select "Vol...".

![2023-03-01-021441_506x138_scrot](https://user-images.githubusercontent.com/87721408/222019747-73273cd4-c714-4c7c-b8b7-5849b9a33ac0.png)
